---
- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version


- name: Download the Go tarball
  get_url: url={{ go_download_location }}
           dest=/usr/local/src/{{ go_tarball }}
           sha256sum={{ go_tarball_checksum }}
  when: go_version|failed or go_version.stdout != go_version_target

- name: Extract the Go tarball
  command: tar -C /usr/local -xf /usr/local/src/{{ go_tarball }}
  when: go_version|failed or go_version.stdout != go_version_target

- name: Compile Go
  shell: cd /usr/local/go/src && ./all.bash
  when: go_version|failed or go_version.stdout != go_version_target

- name: Add Go to PATH
  copy:
    content: "export PATH=$PATH:/usr/local/go/bin"
    dest: /etc/profile.d/golang.sh
  when: go_version|failed or go_version.stdout != go_version_target
