---
- name: Download the Go tarball
  get_url: url={{ go_download_location }}
           dest=/usr/local/src/{{ go_tarball }}
           sha256sum={{ go_tarball_checksum }}

- name: Extract the Go tarball
  command: tar -C /usr/local -xf /usr/local/src/{{ go_tarball }}

- name: Compile Go
  shell: cd /usr/local/go/src && ./all.bash

#
# - name: Add the Go bin directory to the PATH environment variable for all users
#   copy: src=go-bin.sh
#         dest=/etc/profile.d
